config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :desks
  namespace :admin do
    resources :dashboard
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  end
  # Defines the root path route ("/")
   root "desks#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/desk.rb
class Desk < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/base_controller.rb
module Admin
    class BaseController < ApplicationController
      before_action :check_if_admin
  
      private
  
      def check_if_admin
        redirect_to root_path unless current_user.admin?
      end
    end
  end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
    layout 'admin/base'
  
    def index; end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/desks_controller.rb
class DesksController < ApplicationController
  before_action :set_desk, only: %i[ show edit update destroy ]
  #before_action :authenticate_user!, only: [ :show, :edit, :update, :destroy]
  # GET /desks or /desks.json
  def index
    @desks = Desk.all
  end

  # GET /desks/1 or /desks/1.json
  def show
  end

  # GET /desks/new
  def new
    @desk = Desk.new
  end

  # GET /desks/1/edit
  def edit
  end

  # POST /desks or /desks.json
  def create
    @desk = Desk.new(desk_params)

    respond_to do |format|
      if @desk.save
        format.html { redirect_to desk_url(@desk), notice: "Desk was successfully created." }
        format.json { render :show, status: :created, location: @desk }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /desks/1 or /desks/1.json
  def update
    respond_to do |format|
      if @desk.update(desk_params)
        format.html { redirect_to desk_url(@desk), notice: "Desk was successfully updated." }
        format.json { render :show, status: :ok, location: @desk }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /desks/1 or /desks/1.json
  def destroy
    @desk.destroy

    respond_to do |format|
      format.html { redirect_to desks_url, notice: "Desk was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_desk
      @desk = Desk.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def desk_params
      params.require(:desk).permit(:start_time, :end_time, :place)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desks_helper.rb
module DesksHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Hello, welcome to admin section</h1>

app/views/desks/_desk.html.erb
<div id="<%= dom_id desk %>">

  <p>
    <strong>ID :</strong>
    <%= desk.id %>
  </p>
  
  <p>
    <strong>Start time:</strong>
    <%= desk.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= desk.end_time %>
  </p>

  <p>
    <strong>Place:</strong>
    <%= desk.place %>
  </p>

</div>

app/views/desks/_form.html.erb
<%= form_with(model: desk) do |form| %>
  <% if desk.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(desk.errors.count, "error") %> prohibited this desk from being saved:</h2>

      <ul>
        <% desk.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.datetime_field :end_time %>
  </div>

  <div>
    <%= form.label :place, style: "display: block" %>
    <%= form.text_field :place %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/desks/edit.html.erb
<h1>Editing desk</h1>

<%= render "form", desk: @desk %>

<br>

<div>
  <%= link_to "Show this desk", @desk %> |
  <%= link_to "Back to desks", desks_path %>
</div>

app/views/desks/home.html.erb
<html>
<header class="text-center">
<div class="d-flex align-items-center justify-content-center vh-100">
  <div class="centered-element">
  <h1>Welcome to our Hot-Desk App!</h1>
    <div class="my-3">
        <section class="text-center">
            <h4>Experience the convenience of flexible workspace solutions.</43>
                <div class="my-2">
                    <a href="#" class="btn btn-outline-dark">Get Started</a>
                </div>
    </div>
</section>

  </div>
</div>
</header>

</body>
</html>

app/views/desks/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-12">
      <h2>Reservations</h2>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-12">
      <table class="table table-borderless">
        <thead>
          <tr>
          <th scope="col">ID</th>
            <th scope="col">Start time</th>
            <th scope="col">End time</th>
            <th scope="col">Place</th>
          </tr>
        </thead>
        <tbody>
          <% @desks.each do |desk| %>
            <tr>
            <td><%= desk.id %></td>
              <td><%= desk.start_time %></td>
              <td><%= desk.end_time %></td>
              <td><%= link_to desk.place, desk %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
    <div class="row">
    <div class="col-12 mt-3">
      <%= button_to "New reservation", { :action => "new" }, :method => :get, :class => "btn btn-success", class: "btn btn-outline-dark" %>
    </div>
  </div>
</div>

app/views/desks/new.html.erb
<h2>New reservation</h2>
<p> mm/dd/yyyy, hh:mm AM/PM</p>
<%= render "form", desk: @desk %>

<br>

<div>
  <%= link_to "Back to desks", desks_path %>
</div>

app/views/desks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @desk %>

<div>
  <%= link_to "Edit this desk", edit_desk_path(@desk) %> |
  <%= link_to "Back to desks", desks_path %>

  <%= button_to "Destroy this desk", @desk, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md justify-content-between" style="background-color: #696969;">

<span class="navbar-text">
    <% if user_signed_in? %>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-dark"  %>
    <% else %>
        <%= button_to "Sign in", new_user_session_path, class: "btn btn-outline-dark" %> 
    <% end %>
</span>

  <ul class="navbar-nav">
    <li class="nav-item"><a class="btn btn-outline-dark" style="margin-right: 10px;" href="/">Home</a></li>
    <li class="nav-item"><a class="btn btn-outline-dark" style="margin-right: 10px;" href="desks/new">Make new reservation</a></li>
    <li class="nav-item"><a class="btn btn-outline-dark" style="margin-right: 5px;"href="/desks">My reservations</a></li>
  </ul>


</nav>

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='admin'>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hot-Desk App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>